from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from classes import *

class Ui_Professor(object):

    def allstudents(self):
        conn = sqlite3.connect('lms-system.db')
        c = conn.cursor()
        c.execute("SELECT * FROM studentGrades")
        a = c.fetchall()
        studentslist = list()
        for i in a:
            studentslist.append(i[0])
        conn.commit()
        conn.close()
        return studentslist

    def chooseClass(self):

        self.class1exam1Text.setText(str("-"))
        self.class1exam2Text.setText(str("-"))
        self.class1finalText.setText(str("-"))
        #Class2 data
        self.class2exam1Text.setText(str("-"))
        self.class2exam2Text.setText(str("-"))
        self.class2finalText.setText(str("-"))
        #Class3 data
        self.class3exam2Text.setText(str("-"))
        self.class3exam1Text.setText(str("-"))
        self.class3finalText.setText(str("-"))
        #Class4 data
        self.class4exam1Text.setText(str("-"))
        self.class4exam2Text.setText(str("-"))
        self.class4finalText.setText(str("-"))

        if self.dropboxCourse.currentText() == "Select a Class":
            self.class1exam1Text.setEnabled(False)
            self.class1exam2Text.setEnabled(False)
            self.class1finalText.setEnabled(False)
            self.class2exam1Text.setEnabled(False)
            self.class2exam2Text.setEnabled(False)
            self.class2finalText.setEnabled(False)
            self.class3exam1Text.setEnabled(False)
            self.class3exam2Text.setEnabled(False)
            self.class3finalText.setEnabled(False)
            self.class4exam1Text.setEnabled(False)
            self.class4exam2Text.setEnabled(False)
            self.class4finalText.setEnabled(False)

        if self.dropboxCourse.currentText() == "Class1":
            self.class1exam1Text.setEnabled(True)
            self.class1exam2Text.setEnabled(True)
            self.class1finalText.setEnabled(True)
            self.class2exam1Text.setEnabled(False)
            self.class2exam2Text.setEnabled(False)
            self.class2finalText.setEnabled(False)
            self.class3exam1Text.setEnabled(False)
            self.class3exam2Text.setEnabled(False)
            self.class3finalText.setEnabled(False)
            self.class4exam1Text.setEnabled(False)
            self.class4exam2Text.setEnabled(False)
            self.class4finalText.setEnabled(False)

        if self.dropboxCourse.currentText() == "Class2":
            self.class1exam1Text.setEnabled(False)
            self.class1exam2Text.setEnabled(False)
            self.class1finalText.setEnabled(False)
            self.class2exam1Text.setEnabled(True)
            self.class2exam2Text.setEnabled(True)
            self.class2finalText.setEnabled(True)
            self.class3exam1Text.setEnabled(False)
            self.class3exam2Text.setEnabled(False)
            self.class3finalText.setEnabled(False)
            self.class4exam1Text.setEnabled(False)
            self.class4exam2Text.setEnabled(False)
            self.class4finalText.setEnabled(False)

        if self.dropboxCourse.currentText() == "Class3":
            self.class1exam1Text.setEnabled(False)
            self.class1exam2Text.setEnabled(False)
            self.class1finalText.setEnabled(False)
            self.class2exam1Text.setEnabled(False)
            self.class2exam2Text.setEnabled(False)
            self.class2finalText.setEnabled(False)
            self.class3exam1Text.setEnabled(True)
            self.class3exam2Text.setEnabled(True)
            self.class3finalText.setEnabled(True)
            self.class4exam1Text.setEnabled(False)
            self.class4exam2Text.setEnabled(False)
            self.class4finalText.setEnabled(False)

        if self.dropboxCourse.currentText() == "Class4":
            self.class1exam1Text.setEnabled(False)
            self.class1exam2Text.setEnabled(False)
            self.class1finalText.setEnabled(False)
            self.class2exam1Text.setEnabled(False)
            self.class2exam2Text.setEnabled(False)
            self.class2finalText.setEnabled(False)
            self.class3exam1Text.setEnabled(False)
            self.class3exam2Text.setEnabled(False)
            self.class3finalText.setEnabled(False)
            self.class4exam1Text.setEnabled(True)
            self.class4exam2Text.setEnabled(True)
            self.class4finalText.setEnabled(True)

    def populateFields(self):
        conn = sqlite3.connect('lms-system.db')
        c = conn.cursor()
        usernameValue =  (self.dropboxStudents.currentText(),)
        print(usernameValue)
        c.execute('SELECT * FROM studentGrades WHERE user=?', usernameValue)
        a = c.fetchone()
        print(a)
        conn.commit()
        conn.close()

        students = grades( a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7], a[8], a[9], a[10], a[11], a[12], a[13], a[14], a[15], a[16])
        print(students)



        if self.dropboxCourse.currentText() == "Select a Class":
            #Class1 data
            self.class1exam1Text.setText(str("-"))
            self.class1exam2Text.setText(str("-"))
            self.class1finalText.setText(str("-"))
            #Class2 data
            self.class2exam1Text.setText(str("-"))
            self.class2exam2Text.setText(str("-"))
            self.class2finalText.setText(str("-"))
            #Class3 data
            self.class3exam2Text.setText(str("-"))
            self.class3exam1Text.setText(str("-"))
            self.class3finalText.setText(str("-"))
            #Class4 data
            self.class4exam1Text.setText(str("-"))
            self.class4exam2Text.setText(str("-"))
            self.class4finalText.setText(str("-"))

        if self.dropboxCourse.currentText() == "Class1":
            #Class1 data
            self.class1exam1Text.setText(str(students.class1exam1.value()))
            self.class1exam2Text.setText(str(students.class1exam2.value()))
            self.class1finalText.setText(str(students.class1final.value()))
            #Class2 data
            self.class2exam1Text.setText(str("-"))
            self.class2exam2Text.setText(str("-"))
            self.class2finalText.setText(str("-"))
            #Class3 data
            self.class3exam2Text.setText(str("-"))
            self.class3exam1Text.setText(str("-"))
            self.class3finalText.setText(str("-"))
            #Class4 data
            self.class4exam1Text.setText(str("-"))
            self.class4exam2Text.setText(str("-"))
            self.class4finalText.setText(str("-"))

        if self.dropboxCourse.currentText() == "Class2":
            #Class1 data
            self.class1exam1Text.setText(str("-"))
            self.class1exam2Text.setText(str("-"))
            self.class1finalText.setText(str("-"))
            #Class2 data
            self.class2exam1Text.setText(str(students.class2exam1.value()))
            self.class2exam2Text.setText(str(students.class2exam2.value()))
            self.class2finalText.setText(str(students.class2final.value()))
            #Class3 data
            self.class3exam2Text.setText(str("-"))
            self.class3exam1Text.setText(str("-"))
            self.class3finalText.setText(str("-"))
            #Class4 data
            self.class4exam1Text.setText(str("-"))
            self.class4exam2Text.setText(str("-"))
            self.class4finalText.setText(str("-"))

        if self.dropboxCourse.currentText() == "Class3":
            #Class1 data
            self.class1exam1Text.setText(str("-"))
            self.class1exam2Text.setText(str("-"))
            self.class1finalText.setText(str("-"))
            #Class2 data
            self.class2exam1Text.setText(str("-"))
            self.class2exam2Text.setText(str("-"))
            self.class2finalText.setText(str("-"))
            #Class3 data
            self.class3exam2Text.setText(str(students.class3exam2.value()))
            self.class3exam1Text.setText(str(students.class3exam1.value()))
            self.class3finalText.setText(str(students.class3final.value()))
            #Class4 data
            self.class4exam1Text.setText(str("-"))
            self.class4exam2Text.setText(str("-"))
            self.class4finalText.setText(str("-"))

        if self.dropboxCourse.currentText() == "Class4":
            #Class1 data
            self.class1exam1Text.setText(str("-"))
            self.class1exam2Text.setText(str("-"))
            self.class1finalText.setText(str("-"))
            #Class2 data
            self.class2exam1Text.setText(str("-"))
            self.class2exam2Text.setText(str("-"))
            self.class2finalText.setText(str("-"))
            #Class3 data
            self.class3exam2Text.setText(str("-"))
            self.class3exam1Text.setText(str("-"))
            self.class3finalText.setText(str("-"))
            #Class4 data
            self.class4exam1Text.setText(str(students.class4exam1.value()))
            self.class4exam2Text.setText(str(students.class4exam2.value()))
            self.class4finalText.setText(str(students.class4final.value()))

    def updateGrades(self):
        #Function to update the grades as per Administrator
        #The same function can be used for professors Screen.
        conn = sqlite3.connect('lms-system.db')
        c = conn.cursor()

        st = self.dropboxStudents.currentText()
        #Class1 data
        c1e1 = self.class1exam1Text.text()
        c1e2 = self.class1exam2Text.text()
        c1f = self.class1finalText.text()
        #Class2 data
        c2e1 = self.class2exam1Text.text()
        c2e2 = self.class2exam2Text.text()
        c2f = self.class2finalText.text()
        #Class3 data
        c3e1 = self.class3exam1Text.text()
        c3e2 = self.class3exam2Text.text()
        c3f = self.class3finalText.text()
        #Class4 data
        c4e1 = self.class4exam1Text.text()
        c4e2 = self.class4exam2Text.text()
        c4f = self.class4finalText.text()
        print(c1e1, c1e2, c1f, c2e1, c2e2, c2f, c3e1, c3e2, c3f, c4e1, c4e2, c4f, st)

        if self.dropboxCourse.currentText() == "Class1":
            c.execute("UPDATE studentGrades SET c1e1=?, c1e2=?, c1f=? WHERE user=?", (c1e1, c1e2, c1f, st,))
        if self.dropboxCourse.currentText() == "Class2":
            c.execute("UPDATE studentGrades SET c2e1=?, c2e2=?, c2f=? WHERE user=?", (c2e1, c2e2, c2f, st,))
        if self.dropboxCourse.currentText() == "Class3":
            c.execute("UPDATE studentGrades SET c3e1=?, c3e2=?, c3f=? WHERE user=?", (c3e1, c3e2, c3f, st,))
        if self.dropboxCourse.currentText() == "Class4":
            c.execute("UPDATE studentGrades SET c4e1=?, c4e2=?, c4f=? WHERE user=?", (c4e1, c4e2, c4f, st,))

        conn.commit()
        conn.close()

    def setupUi(self, Professor):
        Professor.setObjectName("Professor")
        Professor.resize(551, 491)
        Professor.setMinimumSize(QtCore.QSize(551, 491))
        Professor.setMaximumSize(QtCore.QSize(551, 491))
        self.centralwidget = QtWidgets.QWidget(Professor)
        self.centralwidget.setObjectName("centralwidget")
        self.dropboxCourse = QtWidgets.QComboBox(self.centralwidget)
        self.dropboxCourse.setGeometry(QtCore.QRect(30, 40, 229, 22))
        self.dropboxCourse.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.dropboxCourse.setObjectName("dropboxCourse")
        courses = ["Select a Class","Class1","Class2","Class3","Class4"]
        self.dropboxCourse.addItems(courses)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 90, 231, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.class2exam1Label = QtWidgets.QLabel(self.layoutWidget)
        self.class2exam1Label.setObjectName("class2exam1Label")
        self.horizontalLayout_4.addWidget(self.class2exam1Label)
        self.class2exam1Text = QtWidgets.QLineEdit(self.layoutWidget)
        self.class2exam1Text.setObjectName("class2exam1Text")
        self.horizontalLayout_4.addWidget(self.class2exam1Text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.class2exam2Label = QtWidgets.QLabel(self.layoutWidget)
        self.class2exam2Label.setObjectName("class2exam2Label")
        self.horizontalLayout_5.addWidget(self.class2exam2Label)
        self.class2exam2Text = QtWidgets.QLineEdit(self.layoutWidget)
        self.class2exam2Text.setObjectName("class2exam2Text")
        self.horizontalLayout_5.addWidget(self.class2exam2Text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.class2finalLabel = QtWidgets.QLabel(self.layoutWidget)
        self.class2finalLabel.setObjectName("class2finalLabel")
        self.horizontalLayout_6.addWidget(self.class2finalLabel)
        self.class2finalText = QtWidgets.QLineEdit(self.layoutWidget)
        self.class2finalText.setObjectName("class2finalText")
        self.horizontalLayout_6.addWidget(self.class2finalText)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 260, 231, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.class3exam1Label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.class3exam1Label_2.setObjectName("class3exam1Label_2")
        self.horizontalLayout_7.addWidget(self.class3exam1Label_2)
        self.class3exam1Text = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.class3exam1Text.setObjectName("class3exam1Text")
        self.horizontalLayout_7.addWidget(self.class3exam1Text)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.class3exam2Label = QtWidgets.QLabel(self.layoutWidget_2)
        self.class3exam2Label.setObjectName("class3exam2Label")
        self.horizontalLayout_8.addWidget(self.class3exam2Label)
        self.class3exam2Text = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.class3exam2Text.setObjectName("class3exam2Text")
        self.horizontalLayout_8.addWidget(self.class3exam2Text)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.class3finalLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.class3finalLabel.setObjectName("class3finalLabel")
        self.horizontalLayout_9.addWidget(self.class3finalLabel)
        self.class3finalText = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.class3finalText.setObjectName("class3finalText")
        self.horizontalLayout_9.addWidget(self.class3finalText)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(280, 260, 231, 151))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.class4exam1Label_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.class4exam1Label_2.setObjectName("class4exam1Label_2")
        self.horizontalLayout_10.addWidget(self.class4exam1Label_2)
        self.class4exam1Text = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.class4exam1Text.setObjectName("class4exam1Text")
        self.horizontalLayout_10.addWidget(self.class4exam1Text)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.class4exam2Label = QtWidgets.QLabel(self.layoutWidget_3)
        self.class4exam2Label.setObjectName("class4exam2Label")
        self.horizontalLayout_11.addWidget(self.class4exam2Label)
        self.class4exam2Text = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.class4exam2Text.setObjectName("class4exam2Text")
        self.horizontalLayout_11.addWidget(self.class4exam2Text)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.class4finalLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.class4finalLabel.setObjectName("class4finalLabel")
        self.horizontalLayout_12.addWidget(self.class4finalLabel)
        self.class4finalText = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.class4finalText.setObjectName("class4finalText")
        self.horizontalLayout_12.addWidget(self.class4finalText)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.class1Label = QtWidgets.QLabel(self.centralwidget)
        self.class1Label.setGeometry(QtCore.QRect(120, 70, 47, 14))
        self.class1Label.setObjectName("class1Label")
        self.class3exam1Label = QtWidgets.QLabel(self.centralwidget)
        self.class3exam1Label.setGeometry(QtCore.QRect(120, 250, 47, 14))
        self.class3exam1Label.setObjectName("class3exam1Label")
        self.class2Label = QtWidgets.QLabel(self.centralwidget)
        self.class2Label.setGeometry(QtCore.QRect(380, 70, 47, 14))
        self.class2Label.setObjectName("class2Label")
        self.class4exam1Label = QtWidgets.QLabel(self.centralwidget)
        self.class4exam1Label.setGeometry(QtCore.QRect(370, 250, 47, 14))
        self.class4exam1Label.setObjectName("class4exam1Label")
        self.savegradesButton = QtWidgets.QPushButton(self.centralwidget)
        self.savegradesButton.setGeometry(QtCore.QRect(140, 420, 80, 22))
        self.savegradesButton.setObjectName("savegradesButton")
        self.okgradesButton = QtWidgets.QPushButton(self.centralwidget)
        self.okgradesButton.setGeometry(QtCore.QRect(230, 420, 80, 22))
        self.okgradesButton.setObjectName("okgradesButton")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(320, 420, 80, 22))
        self.quitButton.setObjectName("quitButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 90, 231, 151))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.class1exam1Label = QtWidgets.QLabel(self.layoutWidget1)
        self.class1exam1Label.setObjectName("class1exam1Label")
        self.horizontalLayout.addWidget(self.class1exam1Label)
        self.class1exam1Text = QtWidgets.QLineEdit(self.layoutWidget1)
        self.class1exam1Text.setObjectName("class1exam1Text")
        self.horizontalLayout.addWidget(self.class1exam1Text)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.class1exam2Label = QtWidgets.QLabel(self.layoutWidget1)
        self.class1exam2Label.setObjectName("class1exam2Label")
        self.horizontalLayout_2.addWidget(self.class1exam2Label)
        self.class1exam2Text = QtWidgets.QLineEdit(self.layoutWidget1)
        self.class1exam2Text.setObjectName("class1exam2Text")
        self.horizontalLayout_2.addWidget(self.class1exam2Text)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.class1finalLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.class1finalLabel.setObjectName("class1finalLabel")
        self.horizontalLayout_3.addWidget(self.class1finalLabel)
        self.class1finalText = QtWidgets.QLineEdit(self.layoutWidget1)
        self.class1finalText.setObjectName("class1finalText")
        self.horizontalLayout_3.addWidget(self.class1finalText)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.dropboxStudents = QtWidgets.QComboBox(self.centralwidget)
        self.dropboxStudents.setGeometry(QtCore.QRect(290, 40, 229, 22))
        self.dropboxStudents.setObjectName("dropboxStudents")
        self.Courses = QtWidgets.QLabel(self.centralwidget)
        self.Courses.setGeometry(QtCore.QRect(30, 20, 55, 16))
        self.Courses.setObjectName("Courses")
        self.S = QtWidgets.QLabel(self.centralwidget)
        self.S.setGeometry(QtCore.QRect(290, 20, 55, 16))
        self.S.setObjectName("S")
        Professor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Professor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 26))
        self.menubar.setObjectName("menubar")
        Professor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Professor)
        self.statusbar.setObjectName("statusbar")
        Professor.setStatusBar(self.statusbar)

        self.retranslateUi(Professor)
        self.savegradesButton.clicked.connect(self.updateGrades)
        self.okgradesButton.clicked.connect(Professor.close)
        self.quitButton.clicked.connect(Professor.close)
        QtCore.QMetaObject.connectSlotsByName(Professor)

        self.class1exam1Text.setEnabled(False)
        self.class1exam2Text.setEnabled(False)
        self.class1finalText.setEnabled(False)
        self.class2exam1Text.setEnabled(False)
        self.class2exam2Text.setEnabled(False)
        self.class2finalText.setEnabled(False)
        self.class3exam1Text.setEnabled(False)
        self.class3exam2Text.setEnabled(False)
        self.class3finalText.setEnabled(False)
        self.class4exam1Text.setEnabled(False)
        self.class4exam2Text.setEnabled(False)
        self.class4finalText.setEnabled(False)

        items = self.allstudents()
        self.dropboxStudents.addItems(items)

        self.dropboxCourse.currentTextChanged.connect(self.chooseClass)
        self.dropboxStudents.currentTextChanged.connect(self.populateFields)

    def retranslateUi(self, Professor):
        _translate = QtCore.QCoreApplication.translate
        Professor.setWindowTitle(_translate("Professor", "MainWindow"))
        self.class2exam1Label.setText(_translate("Professor", "Exam 1:"))
        self.class2exam2Label.setText(_translate("Professor", "Exam 2:"))
        self.class2finalLabel.setText(_translate("Professor", "Final:"))
        self.class3exam1Label_2.setText(_translate("Professor", "Exam 1:"))
        self.class3exam2Label.setText(_translate("Professor", "Exam 2:"))
        self.class3finalLabel.setText(_translate("Professor", "Final:"))
        self.class4exam1Label_2.setText(_translate("Professor", "Exam 1:"))
        self.class4exam2Label.setText(_translate("Professor", "Exam 2:"))
        self.class4finalLabel.setText(_translate("Professor", "Final:"))
        self.class1Label.setText(_translate("Professor", "Class 1:"))
        self.class3exam1Label.setText(_translate("Professor", "Class 3:"))
        self.class2Label.setText(_translate("Professor", "Class 2:"))
        self.class4exam1Label.setText(_translate("Professor", "Class 4:"))
        self.savegradesButton.setText(_translate("Professor", "Save"))
        self.okgradesButton.setText(_translate("Professor", "Ok"))
        self.quitButton.setText(_translate("Professor", "Quit"))
        self.class1exam1Label.setText(_translate("Professor", "Exam 1:"))
        self.class1exam2Label.setText(_translate("Professor", "Exam 2:"))
        self.class1finalLabel.setText(_translate("Professor", "Final:"))
        self.Courses.setText(_translate("Professor", "Classes"))
        self.S.setText(_translate("Professor", "Student"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Professor = QtWidgets.QMainWindow()
    ui = Ui_Professor()
    ui.setupUi(Professor)
    Professor.show()
    sys.exit(app.exec_())
