# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentScreen.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(False)
        MainWindow.resize(547, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.class1Label = QtWidgets.QLabel(self.centralwidget)
        self.class1Label.setGeometry(QtCore.QRect(110, 40, 47, 14))
        self.class1Label.setObjectName("class1Label")
        self.class2Label = QtWidgets.QLabel(self.centralwidget)
        self.class2Label.setGeometry(QtCore.QRect(390, 40, 47, 14))
        self.class2Label.setObjectName("class2Label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 201, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.class1exam1Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.class1exam1Label.setObjectName("class1exam1Label")
        self.horizontalLayout.addWidget(self.class1exam1Label)
        self.class1exam1Text = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.class1exam1Text.setEnabled(False)
        self.class1exam1Text.setObjectName("class1exam1Text")
        self.horizontalLayout.addWidget(self.class1exam1Text)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 110, 201, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.class2exam2Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.class2exam2Label.setObjectName("class2exam2Label")
        self.horizontalLayout_2.addWidget(self.class2exam2Label)
        self.class1exam2Text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.class1exam2Text.setEnabled(False)
        self.class1exam2Text.setObjectName("class1exam2Text")
        self.horizontalLayout_2.addWidget(self.class1exam2Text)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 160, 201, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.class1finalLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.class1finalLabel.setObjectName("class1finalLabel")
        self.horizontalLayout_3.addWidget(self.class1finalLabel)
        self.class1finalText = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.class1finalText.setEnabled(False)
        self.class1finalText.setObjectName("class1finalText")
        self.horizontalLayout_3.addWidget(self.class1finalText)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(310, 60, 201, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.class2exam1Label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.class2exam1Label.setObjectName("class2exam1Label")
        self.horizontalLayout_4.addWidget(self.class2exam1Label)
        self.class2exam1Text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.class2exam1Text.setEnabled(False)
        self.class2exam1Text.setObjectName("class2exam1Text")
        self.horizontalLayout_4.addWidget(self.class2exam1Text)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(310, 110, 201, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.class2exam2Label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.class2exam2Label_2.setObjectName("class2exam2Label_2")
        self.horizontalLayout_5.addWidget(self.class2exam2Label_2)
        self.class2exam2Text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.class2exam2Text.setEnabled(False)
        self.class2exam2Text.setObjectName("class2exam2Text")
        self.horizontalLayout_5.addWidget(self.class2exam2Text)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(310, 160, 201, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.class2finalLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.class2finalLabel.setObjectName("class2finalLabel")
        self.horizontalLayout_6.addWidget(self.class2finalLabel)
        self.class2finalText = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.class2finalText.setEnabled(False)
        self.class2finalText.setObjectName("class2finalText")
        self.horizontalLayout_6.addWidget(self.class2finalText)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(30, 290, 201, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.class3exam1Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.class3exam1Label.setObjectName("class3exam1Label")
        self.horizontalLayout_7.addWidget(self.class3exam1Label)
        self.class3exam1Text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.class3exam1Text.setEnabled(False)
        self.class3exam1Text.setObjectName("class3exam1Text")
        self.horizontalLayout_7.addWidget(self.class3exam1Text)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(30, 340, 201, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.class3exam2Label = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.class3exam2Label.setObjectName("class3exam2Label")
        self.horizontalLayout_8.addWidget(self.class3exam2Label)
        self.class3exam2Text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.class3exam2Text.setEnabled(False)
        self.class3exam2Text.setObjectName("class3exam2Text")
        self.horizontalLayout_8.addWidget(self.class3exam2Text)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(30, 390, 201, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.class3finalLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.class3finalLabel.setObjectName("class3finalLabel")
        self.horizontalLayout_9.addWidget(self.class3finalLabel)
        self.class3finalText = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.class3finalText.setEnabled(False)
        self.class3finalText.setObjectName("class3finalText")
        self.horizontalLayout_9.addWidget(self.class3finalText)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(310, 290, 201, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.class4exam1Label = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.class4exam1Label.setEnabled(False)
        self.class4exam1Label.setObjectName("class4exam1Label")
        self.horizontalLayout_10.addWidget(self.class4exam1Label)
        self.class4exam1Text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.class4exam1Text.setEnabled(False)
        self.class4exam1Text.setObjectName("class4exam1Text")
        self.horizontalLayout_10.addWidget(self.class4exam1Text)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(310, 340, 201, 41))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.class4exam2Label = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.class4exam2Label.setObjectName("class4exam2Label")
        self.horizontalLayout_11.addWidget(self.class4exam2Label)
        self.class4exam2Text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.class4exam2Text.setEnabled(False)
        self.class4exam2Text.setObjectName("class4exam2Text")
        self.horizontalLayout_11.addWidget(self.class4exam2Text)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(310, 390, 201, 41))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.class4finalLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.class4finalLabel.setObjectName("class4finalLabel")
        self.horizontalLayout_12.addWidget(self.class4finalLabel)
        self.class4finalText = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.class4finalText.setEnabled(False)
        self.class4finalText.setObjectName("class4finalText")
        self.horizontalLayout_12.addWidget(self.class4finalText)
        self.class3Label = QtWidgets.QLabel(self.centralwidget)
        self.class3Label.setGeometry(QtCore.QRect(100, 250, 47, 14))
        self.class3Label.setObjectName("class3Label")
        self.class4Label = QtWidgets.QLabel(self.centralwidget)
        self.class4Label.setEnabled(False)
        self.class4Label.setGeometry(QtCore.QRect(390, 250, 47, 14))
        self.class4Label.setObjectName("class4Label")
        self.gpaLabel = QtWidgets.QLabel(self.centralwidget)
        self.gpaLabel.setGeometry(QtCore.QRect(310, 450, 47, 14))
        self.gpaLabel.setObjectName("gpaLabel")
        self.gpaText = QtWidgets.QLineEdit(self.centralwidget)
        self.gpaText.setEnabled(False)
        self.gpaText.setGeometry(QtCore.QRect(340, 450, 153, 19))
        self.gpaText.setObjectName("gpaText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.class1Label.setText(_translate("MainWindow", "Class 1"))
        self.class2Label.setText(_translate("MainWindow", "Class 2"))
        self.class1exam1Label.setText(_translate("MainWindow", "Exam 1:"))
        self.class2exam2Label.setText(_translate("MainWindow", "Exam 2:"))
        self.class1finalLabel.setText(_translate("MainWindow", "Final:"))
        self.class2exam1Label.setText(_translate("MainWindow", "Exam 1:"))
        self.class2exam2Label_2.setText(_translate("MainWindow", "Exam 2:"))
        self.class2finalLabel.setText(_translate("MainWindow", "Final:"))
        self.class3exam1Label.setText(_translate("MainWindow", "Exam 1:"))
        self.class3exam2Label.setText(_translate("MainWindow", "Exam 2:"))
        self.class3finalLabel.setText(_translate("MainWindow", "Final:"))
        self.class4exam1Label.setText(_translate("MainWindow", "Exam 1:"))
        self.class4exam2Label.setText(_translate("MainWindow", "Exam 2:"))
        self.class4finalLabel.setText(_translate("MainWindow", "Final:"))
        self.class3Label.setText(_translate("MainWindow", "Class 3"))
        self.class4Label.setText(_translate("MainWindow", "Class 4"))
        self.gpaLabel.setText(_translate("MainWindow", "GPA:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
